# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Built-in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # General file checks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Prevent files larger than 1MB
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

      # Python specific
      - id: check-ast
      - id: debug-statements
      - id: requirements-txt-fixer

      # Security checks
      - id: detect-private-key
        fail_fast: true

  # Secret scanning with detect-secrets (comprehensive secret detection)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            ckpts/|
            datasets/|
            figures/|
            .*\.lock$|
            .*\.min\.js$|
            .*\.map$|
            package-lock\.json$|
            yarn\.lock$
          )$
        fail_fast: true

  # GitLeaks for additional secret scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        fail_fast: true

  # Azure-specific credential scanning (more comprehensive than basic hooks)
  - repo: local
    hooks:
      - id: azure-credentials-scan
        name: Azure Credentials Scanner
        description: Scans for Azure-specific credentials and secrets
        entry: python3
        args: ['.azure-credentials-scanner.py']
        language: system
        files: '\.(py|js|ts|json|yaml|yml|txt|md|sh|ps1|tf|bicep|cs|java|go)$'
        exclude: '\.secrets\.baseline$|\.git.*|\.azure-credentials-scanner\.py$'
        fail_fast: true

  # Microsoft Security DevOps patterns (additional to detect-secrets)
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: text-unicode-replacement-char
      - id: python-no-log-warn
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      # Additional Microsoft/Azure specific patterns
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # Infrastructure as Code scanning for Azure resources
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.295
    hooks:
      - id: checkov
        args: [
          '--framework', 'terraform,arm,bicep,cloudformation',
          '--skip-check', 'CKV_AZURE_109',  # Skip overly strict checks
          '--quiet'
        ]
        files: '\.(tf|json|yaml|yml|bicep)$'
        fail_fast: true

  # Security linting with bandit
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ['-r', '--format', 'custom', '--configfile', '.bandit']
        fail_fast: true

# Global configuration
default_language_version:
  python: python3.12
