description: inverse folding conditioned on backbone structure - base env v9 checks torch geom

target:
  service: sing
  workspace_name: alpamltws
  name: msrresrchbasicvc

environment:
  image:  inv_fold:base_env_v9
  registry: alpamltacr.azurecr.io



data:
  local_dir: ./datasets
  remote_dir: data/inv_fold/

jobs:
  - name: inverse_folding_train_v1_debug
    sku: 80G4-A100
    preemptible: True
    command:
      - conda activate base
      - echo "cd ../../workspace/"
      - cd ../../workspace/
      - torchrun --nproc_per_node=4 train.py
        --split_json $$AMLT_DATA_DIR/datasets/cath-4.2/chain_set_splits.json
        --map_pkl $$AMLT_DATA_DIR/datasets/cath-4.2/chain_set_map.pkl
        --epochs 40 --lr 1e-2 --weight_decay 0.01 --use_virtual_node
        --mse_weight 0.1 --ce_weight 1.0 --dropout 0.2
        --scheduler_patience 8 --scheduler_factor 0.5
        --num_workers 4 --distributed
        --enable_checkpoint_rollback
        --rollback_patience_factor 0.5
        --batch 64 --use_qkv --num_layers 4 --hidden_dim 32
        --recycle_steps 2 --seed 42 --run_mode regular
        --output_dir $$AMLT_OUTPUT_DIR
      - echo "Training with the supernode completed successfully."
    submit_args:
      max_run_duration_seconds: 86400
      env:
        WANDB_API_KEY: ${WANDB_API_KEY}
        _AZUREML_SINGULARITY_JOB_UAI: ***REMOVED***
        AMLT_DIRSYNC_FREQ: 300
    identity: managed
